### ISSUE TITLE
Player toolbar jiggles in place with this installed

### ISSUE THREAD

**Issue by Sunconure11** [lanAnderson/SeasonInfo#60]
Upon disabling your mod, this no longer happens. This was not present on previous builds.

I am encountering this on 1.19.2. If needed, I can record this.

**Comment by lanAnderson** [comment]
Need more info:

1. Fabric or Forge
2. Which minimap
3. Modlist

**Comment by Sunconure11** [comment]
1. Quilt, so technically, Fabric
2. Xaero's
3. Oh boy...

**Comment by lanAnderson** [comment]
I loaded up a 1.19.2 instance using Quilt and a bunch of common mods, and am not seeing the toolbar issue. I'll at least need the latest.log after it happens, or if you are using a modpack the name of that would be even better.

**Comment by Sunconure11** [comment]
I'll get a log in a little while. It is Christmas, after all.

**Comment by Sunconure11** [comment]
[latest.log](https://github.com/lanAnderson/SeasonHUD/files/13773897/latest.log)

**Comment by lanAnderson** [comment]
I went through and added some of the mods a few at a time, and it looks like the issue is with Exordium. It changes things with GUI rendering and is incompatible with many mods that add their own elements. It looks like the 1.9.4 version fixed many of the incompatibilities, but it wasn't backported to the 1.19.2 version. I don't think it is something I can fix on my side.
