### ISSUE TITLE
Crash with Map Atlases?

### ISSUE THREAD

**Issue by znz10** [lanAnderson/SeasonInfo#78]
**Describe the issue**
- Game crashes when loading in world.

**Minecraft Version**
- 1.20.1

**Mod Version**
- 1.7.19 [Latest]

**Modloader(Fabric/Forge/NeoForge)**
- Fabric

**Modloader Version**
- 0.15.11 [Latest]

**Additional Info (Crashlog/Modlist)**
- https://mclo.gs/ic153XF

**Comment by lanAnderson** [comment]
It looks like you are using MapAtlases 2.6.0 still. If you are using Modrinth, that is the latest version for Fabric, but CurseForge has additional updates for it with a multiplat fork.

Unfortunately I can't support both since they have the same modid, but I believe SeasonHUD 1.7.6 was the last version that had the code for the old version if you want to try that.
